"""inital

Revision ID: 40cc56154025
Revises: 
Create Date: 2025-11-12 20:59:56.081781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cc56154025'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products')),
    sa.UniqueConstraint('name', name=op.f('uq__products__name'))
    )

    op.execute(
        f"INSERT into products (id, name, calories) values ('a1b2c3d4-e5f6-7890-abcd-ef1234567890','Beer', 100);"
    )

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('curr_product_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curr_product_id'], ['products.id'], name=op.f('fk__users__curr_product_id__products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users'))
    )
    op.create_index(op.f('ix__users__chat_id'), 'users', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__users__chat_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###
