"""inital

Revision ID: ec25d41c532a
Revises:
Create Date: 2025-11-11 14:16:13.449731

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec25d41c532a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__products')),
    sa.UniqueConstraint('name', name=op.f('uq__products__name'))
    )
    default_product_id = uuid.uuid4()
    op.execute(
        f"INSERT into products (id, name, calories) values ('a1b2c3d4-e5f6-7890-abcd-ef1234567890','Beer', 100);"
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('curr_product_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('chat_id', name=op.f('uq__users__chat_id')),
    sa.ForeignKeyConstraint(['curr_product_id'], ['products.id'], name=op.f('fk__users__curr_product_id__products'))
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("DELETE FROM products WHERE name = 'Beer'")
    op.drop_table('products')
    # ### end Alembic commands ###